### ISSUE TITLE
Really long running time with strange result...

### ISSUE THREAD

**Issue by PiranhaGreg** [vvanirudh/Pixel-Art#1]
Hi, I just trying this code. I know, this algorithm take some time, but I didn't expect so much...

My attempt (320x200px)

![keen](https://cloud.githubusercontent.com/assets/3635737/7884718/1487bf1a-0620-11e5-9699-65b946c8585d.png)

take **174 minutes** with this result (converted to png)

![keen](https://cloud.githubusercontent.com/assets/3635737/7884749/4c497628-0620-11e5-8f41-4a8343f0ce7c.png)

I need upscale some videos from one old DOS game, but in reasonable time... I'm doing something wrong?

**Comment by vvanirudh** [comment]
I haven't run the program on your image specifically, but as stated in the README, the running time depends on the input image size. Your image size being 320x200 px, is pretty large for my program.

I know that 320x200 essentially is a small size image but since the entire algorithm is coded in python, without any optimization (and since python is extremely slow), the running time is huge.

Off the top of my head, you can workaround this problem in two ways:
1. Scale down the image to very small size (maintaining the aspect ratio). Maybe, 32x20 px and try again. (Easy way)
2. Port the code to C++ which will run quite fast (may need to optimize the code too) (Hard way)

Once I run the program on your image, I may come up with some more solutions. But for now, try this.

**Comment by yvd** [comment]
You didn't do anything wrong, it took us 5 minutes for a small 16x16 pixel
image, we didn't optimize it at all.
